Logistic Reg


In [0]:
import pandas as pd
import pylab as pl
import numpy as np
import scipy.optimize as opt
from sklearn import preprocessing
%matplotlib inline 
import matplotlib.pyplot as plt
import io

In [0]:
#Click here and press Shift+Enter
# !wget -O titanic.csv https://drive.google.com/open?id=1iW9ayIBGdJZLVnhfV-BM21cXGIu6TAdx


pembuatan file upload csv untuk digunakan dalam data tabel

In [2]:
# churn_df = pd.read_csv("titanic.csv")
# churn_df.head()
from google.colab import files
uploaded = files.upload()

Saving titanic.csv to titanic (3).csv


In [3]:
DataTitanic = pd.read_csv(io.StringIO(uploaded['titanic.csv'].decode('utf-8')))
DataTitanic.head(5)

PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S

[5 rows x 12 columns]

Preprosesing

data dibagi 2, data test dan lebel hasil
data tes diambil dari kolom Pclass, Sex,Sibsp dan Parch

In [0]:
# DataTitanic=DataTitanic[['Pclass','Sex','SibSp','Parch']]
X=np.asarray(DataTitanic[['Pclass','Sex','SibSp','Parch']])
# DataTitanic
sex= preprocessing.LabelEncoder()
sex.fit(['female','male'])
X[:,1]=sex.transform(X[:,1]) 
# X
Y=np.asarray(DataTitanic['Survived'])
# Y

normalisasi

In [5]:
from sklearn import preprocessing
X = preprocessing.StandardScaler().fit(X).transform(X)
X[0:5]

array([[ 0.82737724,  0.73769513,  0.43279337, -0.47367361],
       [-1.56610693, -1.35557354,  0.43279337, -0.47367361],
       [ 0.82737724, -1.35557354, -0.4745452 , -0.47367361],
       [-1.56610693, -1.35557354,  0.43279337, -0.47367361],
       [ 0.82737724,  0.73769513, -0.4745452 , -0.47367361]])

pembuatan data dengan komposisi 9/1 data set dan data train

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X, Y, test_size=0.1, random_state=4)
print ('Train set:', X_train.shape,  y_train.shape)
print ('Test set:', X_test.shape,  y_test.shape)

Train set: (801, 4) (801,)
Test set: (90, 4) (90,)


pembuatan model dengan logistik reg

In [7]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
LR = LogisticRegression(C=0.01, solver='liblinear').fit(X_train,y_train)
LR

LogisticRegression(C=0.01, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)

penampilan hasil

In [8]:
yhat = LR.predict(X_test)
yhat

array([0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1])

persentase untuk setiap kasusnya

In [9]:
yhat_prob = LR.predict_proba(X_test)
yhat_prob

array([[0.75834497, 0.24165503],
       [0.75834497, 0.24165503],
       [0.417028  , 0.582972  ],
       [0.21300902, 0.78699098],
       [0.78862892, 0.21137108],
       [0.54282749, 0.45717251],
       [0.29872072, 0.70127928],
       [0.43643105, 0.56356895],
       [0.53476075, 0.46523925],
       [0.65873881, 0.34126119],
       [0.75834497, 0.24165503],
       [0.67634069, 0.32365931],
       [0.32265273, 0.67734727],
       [0.77258293, 0.22741707],
       [0.22660952, 0.77339048],
       [0.65873881, 0.34126119],
       [0.75834497, 0.24165503],
       [0.47936027, 0.52063973],
       [0.75834497, 0.24165503],
       [0.31559922, 0.68440078],
       [0.65873881, 0.34126119],
       [0.75834497, 0.24165503],
       [0.75834497, 0.24165503],
       [0.75834497, 0.24165503],
       [0.31559922, 0.68440078],
       [0.42846361, 0.57153639],
       [0.21300902, 0.78699098],
       [0.22660952, 0.77339048],
       [0.75834497, 0.24165503],
       [0.75834497, 0.24165503],
       [0.

hasil persision dan recall

In [10]:
from sklearn.metrics import classification_report, confusion_matrix

print (classification_report(y_test, yhat))


              precision    recall  f1-score   support

           0       0.88      0.90      0.89        63
           1       0.76      0.70      0.73        27

    accuracy                           0.84        90
   macro avg       0.82      0.80      0.81        90
weighted avg       0.84      0.84      0.84        90

